version: '2.4'
services:
  saheeli:
    build:
      context: .
      dockerfile: Dockerfile.orchestrator
    volumes:
      - .:/app
      - ./results:/app/results
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    healthcheck:
      test: ["CMD", "python", "-m", "saheeli.healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 3
    command: ["python", "-m", "saheeli.cli"]

  servo:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./results:/workspace
    healthcheck:
      test: ["CMD", "python", "-m", "servo.healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 3
